#server config
server:
  port: 8088
spring:
  application:
    name: security-demo
  #redis缓存配置
  redis:
    database: 0
    host: 127.0.0.1
    password: foobared
    port: 6379
    pool:
      max-idle: 300
      min-idel: 0
      max-active: 1000
      max-wait: 3000
  http:
      encoding:
        force: true
  datasource:
      druid:
          url: jdbc:mysql://127.0.0.1:3306/oauth2?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 5
          min-idle: 6
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          filters: stat,wall,log4j
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

system:
#客户端配置
  client:
    #clients[0]:
      clientId: lvhaibao
      clientSecret: 123456


